name: Test and build signed artifacts on release

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build_apk:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: app/keystore

      - name: Run tests and build release artifacts
        run: |
          ./gradlew assembleRelease --stacktrace

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: app/build/outputs/apk/release/app-release.apk
          
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: release 
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload release
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/app-release.apk
          asset_name: LearnNumbers.apk
          asset_content_type: application/zip
